Veewee::Session.declare({
  :cpu_count => '1',
  :memory_size=> '256',
  :disk_size => '512',
  :disk_format => 'VDI',
  :hostiocache => 'off',
  :os_type_id => 'Linux26',
  #:iso_file => "CorePlus-5.0.2.iso",
  #:iso_src => "http://distro.ibiblio.org/tinycorelinux/5.x/x86/release/CorePlus-5.0.2.iso",
  #:iso_md5 => '406bf68601aed0a6e29114d4eb280d1d',
  :iso_file => "Core-5.0.2.iso",
  :iso_src => "http://distro.ibiblio.org/tinycorelinux/5.x/x86/release/Core-5.0.2.iso",
  :iso_md5 => 'e67e0932baea447fcd54fdbe13f3a9b5',
  :iso_download_timeout => "1000",
  :boot_wait => "3",
  :boot_cmd_sequence => [
    #'<Wait><Esc><Wait>core<Enter>','<Wait>' * 5, # for CorePlus.iso
    '<Wait><Enter>','<Wait>' * 5, # for Core.iso
    'sudo echo http://kambing.ui.ac.id/tinycorelinux/ > /opt/tcemirror<Enter>',
    'fdisk -l<Enter>',
    'sudo fdisk /dev/sda<Enter>',
    'n<Enter>p<Enter>1<Enter><Enter><Enter>',
    't<Enter>83<Enter>w<Enter><Wait><Wait>',
    'sudo mkfs.ext3 /dev/sda1<Enter>',
    '<Wait>'*3,'fdisk -l<Enter>',
    'sudo mkdir /mnt/sda1<Enter>',
    'sudo mount /dev/sda1 /mnt/sda1<Enter>',
    'sudo mkdir -p /mnt/sda1/boot/grub<Enter>',
    'sudo mount /dev/sr0 /mnt/sr0<Enter>',
    'cd /mnt/sr0/boot<Enter>sudo cp core.gz vmlinuz /mnt/sda1/boot/<Enter><Wait>cd<Enter>',
    'tce-load -wi grub2<Enter>', '<Wait>'*35,
    'sudo grub-install --boot-directory=/mnt/sda1/boot /dev/sda<Enter>',
    'sudo sh -c "cat > /mnt/sda1/boot/grub/grub.cfg" << EOF<Enter>',
    'set timeout=0<Enter>',
    'insmod ext2<Enter>',
    'menuentry \'Core Linux\' {<Enter>',
    '  set root=(hd0,1)<Enter>',
    '  linux (hd0,1)/boot/vmlinuz waitusb=0 noswap root=/dev/sda1 tce=sda1<Enter>',
    '  initrd (hd0,1)/boot/core.gz<Enter>',
    '}<Enter>',
    'EOF<Enter>',
    'sudo mkdir /mnt/sda1/tce<Enter>',
    'sudo touch /mnt/sda1/tce/mydata.tgz<Enter>',
    'tce-load -wi coreutils<Enter>', '<Wait>'*45,
    'sudo cp /usr/local/bin/base64 /mnt/sda1/tce/<Enter><Wait>',
    'tce-load -wi curl<Enter>', '<Wait>'*50,
    'sudo curl -o /mnt/sda1/tce/vagrant_keys https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub<Enter>',
    '<Wait>'*12,
    'sudo reboot<Enter>', '<Wait>'*22,
    'mv /mnt/sda1/tce/base64 /home/tc/<Enter>',
    'tce-load -wi openssh<Enter>', '<Wait>'*55,
    #'tce-ab<Enter>s', '<Wait>'*6,'openssh<Enter>', '<Wait>'*10,'q<Wait>I', '<Wait>'*55,'q<Wait>',
    'sudo cp /usr/local/etc/ssh/sshd_config.example /usr/local/etc/ssh/sshd_config<Enter>',
    'sudo sh -c "cat >> /opt/.filetool.lst" << EOF<Enter>',
    '/etc/sudoers<Enter>',
    '/etc/passwd<Enter>',
    '/etc/shadow<Enter>',
    '/usr/local/etc/ssh<Enter>',
    '/lib/modules/3.8.10-tinycore/misc<Enter>',
    'EOF<Enter>',
    'sudo sed -i s/box/core/g /opt/bootsync.sh<Enter>',
    'sudo sh -c "cat >> /opt/bootsync.sh" << EOF<Enter>',
    '/bin/mkdir -p /vagrant<Enter>',
    '/bin/chown -R tc:staff /vagrant<Enter>',
    '/bin/chmod -R 777 /vagrant<Enter><Enter>',
    '/usr/local/etc/init.d/openssh start<Enter><Enter>',
    '/sbin/depmod -a<Enter>',
    '/sbin/modprobe vboxguest<Enter>',
    '/sbin/modprobe vboxsf<Enter><Enter>',
    '/bin/ln -s /home/tc/bin/mount.vboxsf /sbin/mount.vboxsf<Enter>',
    '/bin/ln -s /home/tc/bin/shutdown /sbin/shutdown<Enter>',
    'EOF<Enter>',
    'sudo passwd tc<Enter><Wait>',
    'vagrant<Enter><Wait>',
    'vagrant<Enter>',
    'ifconfig eth0 | grep inet<Enter>',
    'mkdir -p /home/tc/bin<Enter>',
    'cat > /home/tc/bin/shutdown << EOF<Enter>',
    '#/bin/sh<Enter>',
    'poweroff -d 4<Enter>',
    'EOF<Enter>',
    'chmod 755 /home/tc/bin/shutdown<Enter><Wait>',
    #'sudo filetool.sh -b<Enter>',
    'sudo /usr/local/etc/init.d/openssh start<Enter>',
    'exit<Enter>'
],
  #:kickstart_port => "7122",
  #:kickstart_timeout => "10000",
  #:kickstart_file => "preseed.cfg",
  :ssh_login_timeout => "10000",
  :ssh_user => "tc",
  :ssh_password => "vagrant",
  :ssh_key => "",
  :ssh_host_port => "7222",
  :ssh_guest_port => "22",
  :sudo_cmd => "echo '%p'|sudo -S sh '%f'",
  :shutdown_cmd => "/home/tc/bin/shutdown",
  :postinstall_files => [ "vbox-ga_tar_gz.sh", "postinstall.sh"],
  :postinstall_timeout => "10000"
})
