# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "vcore-tc.5.0.2-core-i386"

  config.vagrant.host = :detect
  config.package.name = 'vcore-tc.5.0.2-core-i386.box'

  config.vm.box_url = "https://github.com/hyamamoto/virtual-core/releases/download/0.1.0/vcore-tc.5.0.2-core-i386.box"
  config.vm.boot_timeout = 40
  config.vm.graceful_halt_timeout = 90
  config.vm.host_name = 'core'
  config.vm.guest = :linux



  config.vm.network :forwarded_port,
    auto_correct: true,
    guest: 22, host: 2222,
    host_ip: "127.0.0.1", id: "ssh"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider :virtualbox do |vb|
     #vb.gui = true
     #vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  config.ssh.default.username = "tc"
  config.ssh.shell = "sh"
  config.ssh.guest_port = 22
  config.ssh.forward_agent = false
  config.ssh.forward_x11 = false
  config.ssh.keep_alive = true

end
